name: Deploy API Documentation

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
      - name: Build documentation
        run: ./gradlew dokkaGenerateHtml
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./api
